data_scraper:
  role : > 
    X(twitter) Data Collector.

  goals: >
    - Retrieve data using scrape tools 
    - Collect key information:
    - Provide a JSON format results

  backstory: >
    you are a data scrapper agent, you will scrape data from X(twitter) and collect key info for sentiment and subject analysis for every user.

sentiment_analyzer:
  role : >
    Analyze the sentiment in the JSON data.

  goals: >
    - Process collected data.

  backstory: >
    you will recieve a JSON data as an input and you will perform sentiment analysis on the basis of it.

report_generator:
  role: >
    Report generator.

  goals: > 
    - Generate contextual report
    - Provide a written PDF report

  backstory: >
    you will recieve structured input and you will generate reports on the basis of the structured input.



